/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/campus.glb 
Author: Nyabsino KMM (https://sketchfab.com/nyabsino)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/visualization-3d-basic-campus-7a2adf11dadf48289a7ee82692b43965
Title: Visualization (3D): Basic Campus
*/

import { useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { useLayoutEffect, useRef } from "react";

export function Campus(props) {
  const { nodes, materials } = useGLTF("/models/campus.glb");

  const ref = useRef(null);

  useLayoutEffect(() => {
    gsap.quickSetter(ref.current, "rotate", "deg");
  }, []);

  useLayoutEffect(() => {
    if (ref.current) {
      gsap.to(ref.current.rotation, {
        y: "+=90",
        duration: 750,
        repeat: -1,
        ease: "linear",
      });
    }
  }, []);

  return (
    <group ref={ref} {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 0.67, 0]}>
          <mesh
            geometry={nodes.mid_building_roof_white_shd_0.geometry}
            material={materials.roof_white_shd}
          />
          <mesh
            geometry={nodes.mid_building_walls_shd_0.geometry}
            material={materials.walls_shd}
          />
          <mesh
            geometry={nodes.mid_building_windows_shd_0.geometry}
            material={materials.windows_shd}
          />
          <mesh
            geometry={nodes.mid_building_pavement_shd_0.geometry}
            material={materials.pavement_shd}
          />
        </group>
        <mesh
          geometry={nodes.third_building_glass_frame_shd_0.geometry}
          material={materials.glass_frame_shd}
        />
        <mesh
          geometry={nodes.third_building_walls_shd_0.geometry}
          material={materials.walls_shd}
        />
        <mesh
          geometry={nodes.third_building_windows_shd_0.geometry}
          material={materials.windows_shd}
        />
        <mesh
          geometry={nodes.third_building_roof_white_shd_0.geometry}
          material={materials.roof_white_shd}
        />
        <mesh
          geometry={nodes.third_building_pavement_shd_0.geometry}
          material={materials.pavement_shd}
        />
        <mesh
          geometry={nodes.small_building_roof_white_shd_0.geometry}
          material={materials.roof_white_shd}
        />
        <mesh
          geometry={nodes.small_building_windows_shd_0.geometry}
          material={materials.windows_shd}
        />
        <mesh
          geometry={nodes.small_building_walls_shd_0.geometry}
          material={materials.walls_shd}
        />
        <mesh
          geometry={nodes.small_building_pavement_shd_0.geometry}
          material={materials.pavement_shd}
        />
        <mesh
          geometry={nodes.parking_shade_walls_shd_0.geometry}
          material={materials.walls_shd}
        />
        <mesh
          geometry={nodes.parking_shade_roof_white_shd_0.geometry}
          material={materials.roof_white_shd}
        />
        <mesh
          geometry={nodes.grass_pane2_pot_farme_shd_0.geometry}
          material={materials.pot_farme_shd}
        />
        <mesh
          geometry={nodes.grass_pane2_grass_shd_0.geometry}
          material={materials.grass_shd}
        />
        <mesh
          geometry={nodes.grass_pane1_pot_farme_shd_0.geometry}
          material={materials.pot_farme_shd}
        />
        <mesh
          geometry={nodes.grass_pane1_grass_shd_0.geometry}
          material={materials.grass_shd}
        />
        <mesh
          geometry={nodes.grass_pane3_pot_farme_shd_0.geometry}
          material={materials.pot_farme_shd}
        />
        <mesh
          geometry={nodes.grass_pane3_grass_shd_0.geometry}
          material={materials.grass_shd}
        />
        <mesh
          geometry={nodes.grass_pane4_pot_farme_shd_0.geometry}
          material={materials.pot_farme_shd}
        />
        <mesh
          geometry={nodes.grass_pane4_grass_shd_0.geometry}
          material={materials.grass_shd}
        />
        <mesh
          geometry={nodes.polySurface20_grass_shd_0.geometry}
          material={materials.grass_shd}
        />
        <mesh
          geometry={nodes.pavement_pot_farme_shd_0.geometry}
          material={materials.pot_farme_shd}
        />
        <mesh
          geometry={nodes.grass_pane6_pot_farme_shd_0.geometry}
          material={materials.pot_farme_shd}
        />
        <mesh
          geometry={nodes.grass_pane6_grass_shd_0.geometry}
          material={materials.grass_shd}
        />
        <mesh
          geometry={nodes.grass_pane7_grass_shd_0.geometry}
          material={materials.grass_shd}
        />
        <mesh
          geometry={nodes.grass_pane7_pot_farme_shd_0.geometry}
          material={materials.pot_farme_shd}
        />
        <mesh
          geometry={nodes.grass_pane8_pot_farme_shd_0.geometry}
          material={materials.pot_farme_shd}
        />
        <mesh
          geometry={nodes.grass_pane8_grass_shd_0.geometry}
          material={materials.grass_shd}
        />
        <mesh
          geometry={nodes.grass_pane9_pot_farme_shd_0.geometry}
          material={materials.pot_farme_shd}
        />
        <mesh
          geometry={nodes.grass_pane9_grass_shd_0.geometry}
          material={materials.grass_shd}
        />
        <mesh
          geometry={nodes.grass_pane10_pot_farme_shd_0.geometry}
          material={materials.pot_farme_shd}
        />
        <mesh
          geometry={nodes.grass_pane10_grass_shd_0.geometry}
          material={materials.grass_shd}
        />
        <mesh
          geometry={nodes.grass_pane11_pot_farme_shd_0.geometry}
          material={materials.pot_farme_shd}
        />
        <mesh
          geometry={nodes.grass_pane11_grass_shd_0.geometry}
          material={materials.grass_shd}
        />
        <mesh
          geometry={nodes.polySurface19_grass_shd_0.geometry}
          material={materials.grass_shd}
        />
        <mesh
          geometry={nodes.grass_pane13_pot_farme_shd_0.geometry}
          material={materials.pot_farme_shd}
        />
        <mesh
          geometry={nodes.grass_pane13_grass_shd_0.geometry}
          material={materials.grass_shd}
        />
        <mesh
          geometry={nodes.pavement2_pavement_shd_0.geometry}
          material={materials.pavement_shd}
          position={[0, 0, -0.087]}
        />
        <mesh
          geometry={nodes.pavement1_pavement_shd_0.geometry}
          material={materials.pavement_shd}
        />
        <mesh
          geometry={nodes.pavement3_pavement_shd_0.geometry}
          material={materials.pavement_shd}
        />
        <mesh
          geometry={nodes.pavement4_pavement_shd_0.geometry}
          material={materials.pavement_shd}
        />
        <mesh
          geometry={nodes.polySurface18_floor_shd_0.geometry}
          material={materials.floor_shd}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/campus.glb");
